version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: yapsed
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: collectors_hub
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d 

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgres://yapsed:12345@db:5432/collectors_hub
      # Proje gereksinimi: JWT Token tabanlı authentication [cite: 24]
      JWT_SECRET: supersecretkey 
    depends_on:
      - db